image: node:18.18

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install and Test
          script:
            - yarn install
            - yarn test -- --maxWorkers=20%
            - yarn e2e
  branches:
    master:
      - step:
          name: Install and Test
          script:
            - yarn install
            - yarn test -- --maxWorkers=20%
            - yarn e2e
  custom:
      deploy-to-vm:
        - step:
            name: Install and Test
            script:
              - yarn install
              - yarn test -- --maxWorkers=20%
              - yarn e2e
        - step:
            name: Deploy to VM
            deployment: production
            script:
              - unset CI
              - export REACT_APP_DATA_API_HOST=$DATA_API_HOST
              - export REACT_APP_USER_API_HOST=$USER_API_HOST
              - export REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
              - export REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
              - export REACT_APP_AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
              - export REACT_APP_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
              - export HTTPS_VALUE=$HTTPS
              - yarn install
              - yarn build
              - pipe: atlassian/ssh-run:0.7.0
                variables:
                  SSH_USER: 'root'
                  SERVER: $HOST_ADDRESS
                  PORT: $HOST_PORT_1
                  COMMAND: "if [ -d rdg-portal/ ]; then rm -rf rdg-portal/*; fi"
              - pipe: atlassian/rsync-deploy:0.11.0
                variables:
                  USER: 'root'
                  SERVER: $HOST_ADDRESS
                  REMOTE_PATH: 'rdg-portal/'
                  LOCAL_PATH: 'build/*'
                  SSH_PORT: $HOST_PORT_1
              - pipe: atlassian/ssh-run:0.7.0
                variables:
                  SSH_USER: 'root'
                  SERVER: $HOST_ADDRESS
                  PORT: $HOST_PORT_2
                  COMMAND: "if [ -d rdg-portal/ ]; then rm -rf rdg-portal/*; fi"
              - pipe: atlassian/rsync-deploy:0.11.0
                variables:
                  USER: 'root'
                  SERVER: $HOST_ADDRESS
                  REMOTE_PATH: 'rdg-portal/'
                  LOCAL_PATH: 'build/*'
                  SSH_PORT: $HOST_PORT_2     
      quick-deploy:
        - step:
            name: Deploy to VM
            deployment: production
            script:
              - unset CI
              - export REACT_APP_DATA_API_HOST=$DATA_API_HOST
              - export REACT_APP_USER_API_HOST=$USER_API_HOST
              - export REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
              - export REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
              - export REACT_APP_AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
              - export REACT_APP_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
              - export HTTPS_VALUE=$HTTPS
              - yarn install
              - yarn build
              - pipe: atlassian/ssh-run:0.7.0
                variables:
                  SSH_USER: 'root'
                  SERVER: $HOST_ADDRESS
                  PORT: $HOST_PORT_1
                  COMMAND: "if [ -d rdg-portal/ ]; then rm -rf rdg-portal/*; fi"
              - pipe: atlassian/rsync-deploy:0.11.0
                variables:
                  USER: 'root'
                  SERVER: $HOST_ADDRESS
                  REMOTE_PATH: 'rdg-portal/'
                  LOCAL_PATH: 'build/*'
                  SSH_PORT: $HOST_PORT_1
              - pipe: atlassian/ssh-run:0.7.0
                variables:
                  SSH_USER: 'root'
                  SERVER: $HOST_ADDRESS
                  PORT: $HOST_PORT_2
                  COMMAND: "if [ -d rdg-portal/ ]; then rm -rf rdg-portal/*; fi"
              - pipe: atlassian/rsync-deploy:0.11.0
                variables:
                  USER: 'root'
                  SERVER: $HOST_ADDRESS
                  REMOTE_PATH: 'rdg-portal/'
                  LOCAL_PATH: 'build/*'
                  SSH_PORT: $HOST_PORT_2  
